SELECT
    MEMBER_NAME, 
    REVIEW_TEXT, 
    DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW A
JOIN (
    SELECT 
        R.MEMBER_ID, 
        MEMBER_NAME, 
        RANK() OVER(ORDER BY CNT DESC) AS RANKING
    FROM (
        SELECT *, COUNT(MEMBER_ID) AS CNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    ) AS R
    JOIN MEMBER_PROFILE M on R.MEMBER_ID = M.MEMBER_ID
) B
ON A.MEMBER_ID = B.MEMBER_ID
WHERE B.RANKING = 1
ORDER BY REVIEW_DATE, REVIEW_TEXT
